version: '3.1'
services:

  mysql-api:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: fairAPI
      DB_DATABASE : fairAPI
      # DB_IP  : localhost
      DB_PORT : 3307

    ports:
      - "3307:3306"

  my-fair-api:    
    image: m74fairapi:latest 
    container_name: m74fairapi 
    restart: unless-stopped
    environment: 
      MYSQL_URL: root:my-secret-pw@tcp(localhost:3307)/
      TYPE_APP: PROD
      SERVER_API_PORT_SQL: :5000
      SERVER_API_PORT_MEM: :5001
      LOG_FILE: ./fairAPIdocker.log

    ports:      
      - "5000:5000"
      - "5001:5001"

    depends_on:
      - mysql-api
    # Reference https://betterprogramming.pub/setting-up-mysql-database-in-a-docker-d6c69a3e9afe

